#! /bin/sh

# Startup scripts
xrandr --output DP-0 --rotate left --right-of HDMI-0 &
bash ~/.config/polybar/start.sh &
bash /home/thager/.config/conky/Kurhah_1/start.sh &
megasync &
picom &
dunst &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d I II III IV V 
bspc monitor DP-0 -d VI VII VIII IX X

bspc config focused_border_color "#cba6f7"
bspc config active_border_color "#b4befe"
bspc config normal_border_color "#b4befe"

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a megasync state=floating
bspc rule -a MEGAsync state=floating
bspc rule -a steam center=on rectangle=2040x1152+0+0 state=floating
bspc rule -a steamwebhelper center=on rectangle=2040x1152+0+0 state=floating
